### ISSUE TITLE
1/5 peers panics and can't reconnect

### ISSUE THREAD

**Issue by phahulin** [c0gent/hydrabadger#1]
Most of the times, after all `./peers[0-4]` are started and begin producing txs, one of them panics ([log](https://gist.github.com/phahulin/4b7d7cb07c2821da89a30f492cb6cd7d)). If restarted, the same error reproduces, so it can't reconnect to other 4 peers anymore, until they're all restarted.
This randomly happens on one of the peers (not the same one).

**Comment by phahulin** [comment]
I'm running
* Ubuntu 16.04
* rustc 1.27.0 (3eda71b00 2018-06-19)
* cargo 1.27.0 (1e95190e5 2018-05-27)

**Comment by c0gent** [comment]
A few bugs have been squashed. Please try again with the updated instructions on the Readme.

Let me know if it works :)

**Comment by phahulin** [comment]
Doesn't look like I can reproduce it anymore :+1:

**Comment by c0gent** [comment]
Great! More command line options coming today for more tests and simulations.
